export const SAMPLE_RECIPES = [
  {
    id: 1,
    name: "Pasta Carbonara",
    category: "Italian",
    time: 25,
    servings: 4,
    difficulty: "Medium",
    description:
      "A classic Roman pasta dish made with eggs, hard cheese, cured pork, and black pepper. Simple, rich, and deeply satisfying.",
    emoji: "🍝",
    photo: "",
    videoUrl: "https://www.youtube.com/watch?v=3AAdKl1UYZs",
    tags: ["pasta", "quick", "dinner"],
    ingredients: [
      "400g spaghetti",
      "200g guanciale or pancetta",
      "4 egg yolks",
      "1 whole egg",
      "100g Pecorino Romano",
      "50g Parmesan",
      "Black pepper",
      "Salt",
    ],
    steps: [
      "Bring a large pot of salted water to a boil and cook the spaghetti al dente.",
      "Meanwhile, fry the guanciale in a pan over medium heat until crispy. Remove from heat.",
      "Whisk together egg yolks, whole egg, grated cheeses, and a generous amount of black pepper.",
      "Reserve 1 cup of pasta cooking water. Drain pasta and add to the pan with guanciale off heat.",
      "Pour egg mixture over pasta, adding pasta water gradually, tossing vigorously to create a creamy sauce.",
      "Serve immediately with extra cheese and pepper.",
    ],
  },
  {
    id: 2,
    name: "Shakshuka",
    category: "Middle Eastern",
    time: 30,
    servings: 2,
    difficulty: "Easy",
    description:
      "Eggs poached in a spiced tomato and pepper sauce. A vibrant one-pan dish perfect for brunch or a cozy dinner.",
    emoji: "🍳",
    photo: "",
    videoUrl: "",
    tags: ["eggs", "brunch", "one-pan"],
    ingredients: [
      "6 large eggs",
      "2 cans crushed tomatoes",
      "1 red bell pepper",
      "1 onion",
      "4 garlic cloves",
      "1 tsp cumin",
      "1 tsp paprika",
      "½ tsp chili flakes",
      "Fresh cilantro",
      "Feta cheese",
    ],
    steps: [
      "Sauté diced onion and bell pepper in olive oil over medium heat for 8 minutes.",
      "Add minced garlic, cumin, paprika, and chili flakes. Cook for 1 minute.",
      "Pour in crushed tomatoes, season with salt and pepper. Simmer for 10 minutes.",
      "Make wells in the sauce and crack eggs into them. Cover and cook until whites are set but yolks remain runny.",
      "Garnish with crumbled feta, fresh cilantro, and serve with crusty bread.",
    ],
  },
  {
    id: 3,
    name: "Mango Sticky Rice",
    category: "Thai",
    time: 45,
    servings: 4,
    difficulty: "Easy",
    description:
      "A beloved Thai dessert featuring sweet glutinous rice drenched in coconut cream, served with ripe fresh mango.",
    emoji: "🥭",
    photo: "",
    videoUrl: "",
    tags: ["dessert", "vegan", "sweet"],
    ingredients: [
      "2 cups glutinous rice",
      "1 can coconut milk",
      "3 tbsp sugar",
      "½ tsp salt",
      "2 ripe mangoes",
      "Sesame seeds",
      "Pandan leaves",
    ],
    steps: [
      "Soak glutinous rice in water for at least 2 hours or overnight.",
      "Steam the rice for 20-25 minutes until tender and translucent.",
      "Heat coconut milk with sugar and salt until dissolved. Reserve ¼ for topping.",
      "Mix the warm rice with the coconut milk mixture. Let rest for 15 minutes.",
      "Peel and slice the mangoes. Serve alongside the sticky rice.",
      "Drizzle reserved coconut cream on top and sprinkle with sesame seeds.",
    ],
  },
  {
    id: 4,
    name: "Beef Tacos",
    category: "Mexican",
    time: 20,
    servings: 6,
    difficulty: "Easy",
    description:
      "Quick and flavorful street-style beef tacos with a homemade spice mix, fresh salsa, and all the classic toppings.",
    emoji: "🌮",
    photo: "",
    videoUrl: "",
    tags: ["quick", "dinner", "crowd-pleaser"],
    ingredients: [
      "500g ground beef",
      "8 corn tortillas",
      "1 onion",
      "2 tomatoes",
      "Cilantro",
      "Lime",
      "1 tsp cumin",
      "1 tsp chili powder",
      "Sour cream",
      "Shredded cheese",
    ],
    steps: [
      "Brown the ground beef in a skillet over high heat, breaking into crumbles.",
      "Season with cumin, chili powder, salt, and pepper. Cook 2 more minutes.",
      "Dice tomatoes and onion finely, mix with chopped cilantro and lime juice for a quick pico de gallo.",
      "Warm tortillas directly over a gas flame or in a dry pan.",
      "Assemble tacos: beef, pico de gallo, sour cream, and cheese. Finish with a squeeze of lime.",
    ],
  },
  {
    id: 5,
    name: "Lemon Tart",
    category: "French",
    time: 90,
    servings: 8,
    difficulty: "Hard",
    description:
      "An elegant French classic — buttery shortcrust pastry filled with silky, tangy lemon curd. A showstopper for any occasion.",
    emoji: "🍋",
    photo: "",
    videoUrl: "",
    tags: ["dessert", "baking", "elegant"],
    ingredients: [
      "200g flour",
      "100g butter",
      "50g icing sugar",
      "4 eggs",
      "180ml lemon juice",
      "Lemon zest",
      "200g sugar",
      "120g butter (for curd)",
      "Pinch of salt",
    ],
    steps: [
      "Make the pastry: rub cold butter into flour and sugar until breadcrumb-like. Add egg yolk and cold water to bind. Chill 30 min.",
      "Roll out pastry and line a tart tin. Blind bake at 180°C for 15 minutes, then 5 minutes without weights.",
      "Whisk eggs, lemon juice, zest, and sugar in a bowl.",
      "Cook mixture in a saucepan over low heat, stirring constantly, until thickened.",
      "Remove from heat, stir in butter until melted. Strain if desired.",
      "Pour curd into tart shell and bake 10 minutes at 160°C. Cool completely before serving.",
    ],
  },
  {
    id: 6,
    name: "Greek Salad",
    category: "Greek",
    time: 10,
    servings: 4,
    difficulty: "Easy",
    description:
      "A refreshing and simple salad with crisp vegetables, briny olives, and creamy feta. No lettuce needed.",
    emoji: "🥗",
    photo: "",
    videoUrl: "",
    tags: ["salad", "vegetarian", "quick", "healthy"],
    ingredients: [
      "4 ripe tomatoes",
      "1 cucumber",
      "1 red onion",
      "200g feta cheese",
      "100g Kalamata olives",
      "1 green pepper",
      "Dried oregano",
      "Extra virgin olive oil",
      "Red wine vinegar",
    ],
    steps: [
      "Chop tomatoes into large chunks and slice the cucumber into thick half-moons.",
      "Thinly slice the red onion and green pepper.",
      "Combine all vegetables in a bowl with the olives.",
      "Place a thick slab of feta on top.",
      "Drizzle generously with olive oil, a splash of vinegar, and a pinch of dried oregano.",
    ],
  },
];
